import {readFile, mkdir, writeFile, readdir} from 'node:fs/promises';
import {siteContacts, contactFacts, contactStrip, contactConfirmation} from './site-contacts.mjs';

const site = new URL('../static-site/', import.meta.url);
const locales = {
  en: {prefix: '', work: 'Our work', electrical: 'Electrical engineering & installation', rates: 'Work with Arcadian', intro: 'Renovation, finishing and facade work. Photographs and descriptions of completed projects.', electricalIntro: 'Electrical work, documented from design through installation. A dedicated portfolio of our electrical projects.', ratesIntro: 'Cooperation terms for employees, independent specialists and crews. Each published position states the payment basis and what is expected.', all: 'All work', finishing: 'Finishing & renovation', facades: 'Facades', electricalFilter: 'Electrical', loading: 'Loading…', more: 'Show more', cta: 'Discuss your project or cooperation with our team.', contact: 'Contact Arcadian', close: 'Close', prev: 'Previous photograph', next: 'Next photograph', homeIntro: 'Site delivery, documented.', homeDescription: 'Explore completed work or discuss joining our delivery teams.', renovationDescription: 'Finishing, renovation and facade projects, with photographs and scope of work.', electricalDescription: 'A dedicated portfolio for electrical engineering and installation.', ratesDescription: 'Cooperation terms for employees, independent specialists and crews.', open: 'Explore →'},
  pl: {prefix: 'pl/', work: 'Nasze realizacje', electrical: 'Projektowanie i instalacje elektryczne', rates: 'Współpraca z Arcadian', intro: 'Renowacje, wykończenia i elewacje. Zdjęcia oraz opisy zrealizowanych projektów.', electricalIntro: 'Prace elektryczne udokumentowane od projektu po montaż. Osobne portfolio naszych realizacji elektrycznych.', ratesIntro: 'Warunki współpracy dla pracowników, samodzielnych specjalistów i brygad. Każda opublikowana pozycja określa podstawę rozliczenia i wymagania.', all: 'Wszystkie prace', finishing: 'Wykończenia i renowacje', facades: 'Elewacje', electricalFilter: 'Elektryka', loading: 'Ładowanie…', more: 'Pokaż więcej', cta: 'Porozmawiaj z naszym zespołem o projekcie lub współpracy.', contact: 'Kontakt z Arcadian', close: 'Zamknij', prev: 'Poprzednie zdjęcie', next: 'Następne zdjęcie', homeIntro: 'Realizacje i współpraca.', homeDescription: 'Zobacz wykonane prace lub porozmawiaj o dołączeniu do naszych zespołów.', renovationDescription: 'Wykończenia, renowacje i elewacje: zdjęcia i zakres wykonanych prac.', electricalDescription: 'Osobne portfolio projektowania i instalacji elektrycznych.', ratesDescription: 'Warunki współpracy dla pracowników, samodzielnych specjalistów i brygad.', open: 'Zobacz →'},
  nl: {prefix: 'nl/', work: 'Onze werken', electrical: 'Elektrisch ontwerp & installatie', rates: 'Samenwerken met Arcadian', intro: 'Renovatie, afwerking en gevelwerken. Foto’s en beschrijvingen van uitgevoerde projecten.', electricalIntro: 'Elektrische werken, van ontwerp tot installatie gedocumenteerd. Een afzonderlijk portfolio van onze elektrische projecten.', ratesIntro: 'Samenwerkingsvoorwaarden voor werknemers, zelfstandige specialisten en ploegen. Elke gepubliceerde positie vermeldt de betalingsbasis en de verwachtingen.', all: 'Alle werken', finishing: 'Afwerking & renovatie', facades: 'Gevels', electricalFilter: 'Elektriciteit', loading: 'Laden…', more: 'Meer tonen', cta: 'Bespreek uw project of samenwerking met ons team.', contact: 'Contact met Arcadian', close: 'Sluiten', prev: 'Vorige foto', next: 'Volgende foto', homeIntro: 'Werken en samenwerking.', homeDescription: 'Bekijk uitgevoerde werken of bespreek samenwerking met onze ploegen.', renovationDescription: 'Afwerking, renovatie en gevelwerken, met foto’s en de uitgevoerde werkzaamheden.', electricalDescription: 'Een afzonderlijk portfolio voor elektrisch ontwerp en installatie.', ratesDescription: 'Samenwerkingsvoorwaarden voor werknemers, zelfstandige specialisten en ploegen.', open: 'Bekijk →'},
};
const escape = (value) => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
const documentCopy = {
  en: {ratesIntro: 'Current rate sheets and cooperation terms, organised by trade. View or download the published PDF documents. The payment basis and working arrangements are stated in each document.', electricalTrade: 'Electricians', facadeTrade: 'Facade specialists', finishingTrade: 'Finishing specialists', crews: 'Subcontractor crews', tradeIntro: 'Published PDF rate sheets and cooperation terms for this trade. View the document or download a copy.', crewsIntro: 'Cooperation with independent crews who have their own vehicle, tools and accommodation. Published PDF documents specify the scope, rates and cooperation terms.', viewRates: 'View rate sheets →'},
  pl: {ratesIntro: 'Aktualne cenniki i warunki współpracy według rodzaju prac. Przeglądaj lub pobierz opublikowane dokumenty PDF. Podstawa rozliczenia i organizacja pracy są określone w każdym dokumencie.', electricalTrade: 'Elektrycy', facadeTrade: 'Specjaliści od elewacji', finishingTrade: 'Pracownicy wykończeniowi', crews: 'Brygady podwykonawcze', tradeIntro: 'Opublikowane cenniki PDF i warunki współpracy dla tego rodzaju prac. Przejrzyj dokument lub pobierz kopię.', crewsIntro: 'Współpraca z samodzielnymi brygadami z własnym samochodem, narzędziami i zakwaterowaniem. Dokumenty PDF określają zakres prac, stawki i warunki współpracy.', viewRates: 'Zobacz cenniki →'},
  nl: {ratesIntro: 'Actuele tarieflijsten en samenwerkingsvoorwaarden per vakgebied. Bekijk of download de gepubliceerde PDF-documenten. De betalingsbasis en werkafspraken staan in elk document.', electricalTrade: 'Elektriciens', facadeTrade: 'Gevelspecialisten', finishingTrade: 'Afwerkingsspecialisten', crews: 'Onderaannemersploegen', tradeIntro: 'Gepubliceerde PDF-tarieflijsten en samenwerkingsvoorwaarden voor dit vakgebied. Bekijk het document of download een exemplaar.', crewsIntro: 'Samenwerking met zelfstandige ploegen met eigen voertuig, gereedschap en huisvesting. De PDF-documenten beschrijven de werkzaamheden, tarieven en samenwerkingsvoorwaarden.', viewRates: 'Bekijk tarieflijsten →'},
};
const cooperationCopy = {
  en: {employees: 'For employees', employeeOffer: 'Join our team in electrical, facade or finishing work. Select your trade, review the PDF rates and contact us about the role.', crewsOfferTitle: 'For subcontractor crews', crewOffer: 'Independent crews with their own vehicle, tools and accommodation. Review PDF rates and cooperation terms for your team.', employeeAction: 'View trade rates', crewAction: 'View crew terms'},
  pl: {employees: 'Dla pracowników', employeeOffer: 'Dołącz do naszego zespołu przy pracach elektrycznych, elewacyjnych lub wykończeniowych. Wybierz specjalizację, sprawdź stawki w PDF i skontaktuj się z nami w sprawie pracy.', crewsOfferTitle: 'Dla brygad podwykonawczych', crewOffer: 'Samodzielne brygady z własnym samochodem, narzędziami i zakwaterowaniem. Sprawdź stawki w PDF i warunki współpracy dla swojego zespołu.', employeeAction: 'Zobacz stawki dla specjalizacji', crewAction: 'Zobacz warunki dla brygad'},
  nl: {employees: 'Voor werknemers', employeeOffer: 'Werk in ons team aan elektrische installaties, gevels of afwerking. Kies uw vakgebied, bekijk de PDF-tarieven en neem contact op over de functie.', crewsOfferTitle: 'Voor onderaannemersploegen', crewOffer: 'Zelfstandige ploegen met eigen voertuig, gereedschap en huisvesting. Bekijk de PDF-tarieven en samenwerkingsvoorwaarden voor uw ploeg.', employeeAction: 'Bekijk tarieven per vakgebied', crewAction: 'Bekijk voorwaarden voor ploegen'},
};
const cooperationOffers = (copy, section) => `<div class="cooperation-offers">
      <section class="cooperation-offer" aria-labelledby="employee-offer"><h2 id="employee-offer">${copy.employees}</h2><p>${copy.employeeOffer}</p><a class="cooperation-link" href="${section === 'rates' ? '#trade-rates' : '/' + copy.prefix + 'rates/#trade-rates'}">${copy.employeeAction}<span aria-hidden="true">→</span></a></section>
      <section class="cooperation-offer" aria-labelledby="crew-offer"><h2 id="crew-offer">${copy.crewsOfferTitle}</h2><p>${copy.crewOffer}</p><a class="cooperation-link" href="${section === 'subcontractors' ? '#rate-documents' : '/' + copy.prefix + 'subcontractors/'}">${copy.crewAction}<span aria-hidden="true">→</span></a></section>
    </div>`;
const cleanHtml = (value) => value.replace(/&amp;(nbsp|times);/g, '&$1;').replace(/&(?!(?:amp|lt|gt|quot|nbsp|times|copy);|#[0-9]+;|#x[0-9a-f]+;)/gi, '&amp;').replace(/[ \t]+\n/g, '\n');
for (const [locale, copy] of Object.entries(locales)) {
  Object.assign(copy, documentCopy[locale], cooperationCopy[locale]);
  const sourceUrl = new URL(`${copy.prefix}index.html`, site);
  let source = await readFile(sourceUrl, 'utf8');
  if (!source.includes('<!-- site-contacts:start -->') || !source.includes('<!-- site-contacts:end -->')) throw new Error(`Missing public contact section: ${copy.prefix}index.html`);
  source = source.replace(/<!-- site-contacts:start -->[\s\S]*?<!-- site-contacts:end -->/, `<!-- site-contacts:start -->\n          ${contactFacts(locale)}\n          <!-- site-contacts:end -->`);
  source = source.replace(/(<div class="sent-message">)[\s\S]*?(<\/div>)/, `$1${contactConfirmation(locale)}$2`);
  source = source.replace(/(<script type="application\/ld\+json">)([\s\S]*?)(<\/script>)/, (_, start, json, end) => {
    const organization = JSON.parse(json);
    organization.telephone = siteContacts.main.number;
    organization.contactPoint = [{ '@type': 'ContactPoint', telephone: siteContacts.poland.number, contactType: 'Corporate office in Poland' }];
    return `${start}${JSON.stringify(organization)}${end}`;
  });
  source = source.replace(/\/assets\/css\/content\.css\?v=[A-Za-z0-9_-]+/g, '/assets/css/content.css?v=cooperation-20261005');
  const links = `<a href="/${copy.prefix}gallery/">${copy.work}</a><a href="/${copy.prefix}rates/">${copy.rates}</a>`;
  source = source.replace(/(<div class="nav-links" id="nav-links">\s*)([\s\S]*?)(\s*<\/div>)/, (_, start, body, end) => `${start}${body.replace(/<a href="[^\"]*\/#team">[\s\S]*?<\/a>/, '').replace(/<a href="[^\"]*\/#about">[\s\S]*?<\/a>/, '')}${body.includes('/gallery/') ? '' : links}${end}`);
  if (!source.includes('/assets/css/content.css')) source = source.replace('</head>', '  <link href="/assets/css/content.css?v=cooperation-20261005" rel="stylesheet">\n</head>');
  if (!source.includes('id="work-and-cooperation"')) {
    const section = `  <section class="lt" id="work-and-cooperation">\n    <div class="content-wrap">\n      <div class="sect-head"><span class="eyebrow">ARCADIAN</span><h2>${copy.homeIntro}</h2><p>${copy.homeDescription}</p></div>\n      <div class="services-entry">\n        <a href="/${copy.prefix}gallery/"><span class="eyebrow">${copy.finishing} · ${copy.facades}</span><h3>${copy.work}</h3><p>${copy.renovationDescription}</p><span class="entry-link">${copy.open}</span></a>\n        <a href="/${copy.prefix}electrical/"><span class="eyebrow">${copy.electricalFilter}</span><h3>${copy.electrical}</h3><p>${copy.electricalDescription}</p><span class="entry-link">${copy.open}</span></a>\n        <a href="/${copy.prefix}rates/"><span class="eyebrow">ARCADIAN</span><h3>${copy.rates}</h3><p>${copy.ratesDescription}</p><span class="entry-link">${copy.open}</span></a>\n      </div>\n    </div>\n  </section>\n\n`;
    source = source.replace('  <section class="lt blueprint products"', section + '  <section class="lt blueprint products"');
  }
  await writeFile(sourceUrl, cleanHtml(source));
  const trades = [['electrical', copy.electricalTrade, 'rates/electrical'], ['facades', copy.facadeTrade, 'rates/facades'], ['finishing', copy.finishingTrade, 'rates/finishing'], ['subcontractors', copy.crews, 'subcontractors']];
  for (const section of ['gallery', 'electrical', 'rates', ...trades.map(([, , path]) => path)]) {
    const trade = trades.find(([, , path]) => path === section);
    const isDocument = section === 'rates' || Boolean(trade);
    const title = trade ? trade[1] : section === 'rates' ? copy.rates : section === 'electrical' ? copy.electrical : copy.work;
    const intro = trade ? (trade[0] === 'subcontractors' ? copy.crewsIntro : copy.tradeIntro) : section === 'rates' ? copy.ratesIntro : section === 'electrical' ? copy.electricalIntro : copy.intro;
    let head = source.slice(0, source.indexOf('  <main class="main">'));
    if (isDocument) head = head.replace('<nav class="nav on-dark" id="site-nav">', '<nav class="nav on-dark" id="site-nav" aria-label="ARCADIAN">');
    head = head.replace(/<title>[^<]+<\/title>/, `<title>${title} — ARCADIAN</title>`);
    head = head.replace(/(<meta (?:name="description"|property="og:description"|name="twitter:description") content=")[^"]+("[^>]*>)/g, `$1${escape(intro)}$2`);
    head = head.replace(/(<meta (?:property="og:title"|name="twitter:title") content=")[^"]+("[^>]*>)/g, `$1${escape(title)} — ARCADIAN$2`);
    head = head.replace(/(<link rel="canonical" href="https:\/\/arcadian-eu.com\/)[^"]*(">)/, `$1${copy.prefix}${section}/$2`);
    head = head.replace(/(<meta property="og:url" content="https:\/\/arcadian-eu.com\/)[^"]*(">)/, `$1${copy.prefix}${section}/$2`);
    head = head.replace(/(<link rel="alternate" hreflang="(en|nl|pl|x-default)" href=")[^"]+(">)/g, (_, before, lang, after) => `${before}https://arcadian-eu.com/${lang === 'pl' || lang === 'nl' ? lang + '/' : ''}${section}/${after}`);
    head = head.replace(/(<div class="lang">)[\s\S]*?(<\/div>)/, `$1<a href="/gallery/" aria-label="English"${locale === 'en' ? ' class="on"' : ''}>EN</a><a href="/pl/gallery/" aria-label="Polski"${locale === 'pl' ? ' class="on"' : ''}>PL</a><a href="/nl/gallery/" aria-label="Nederlands"${locale === 'nl' ? ' class="on"' : ''}>NL</a>$2`).replaceAll('gallery/" aria-label=', `${section}/" aria-label=`);
    const footer = source.slice(source.indexOf('  <footer'), source.indexOf('</footer>') + '</footer>'.length);
    const documentNav = isDocument ? `<nav class="document-sections" id="trade-rates" aria-label="${copy.rates}">${trades.map(([sector, label, path]) => `<a href="/${copy.prefix}${path}/"${trade?.[0] === sector ? ' aria-current="page"' : ''}><span class="eyebrow">PDF</span><h2>${label}</h2><span class="entry-link">${copy.viewRates}</span></a>`).join('')}</nav>` : '';
    const filters = isDocument || section === 'electrical' ? '' : `<div class="content-filters" role="group" aria-label="${copy.work}">${[['', copy.all], ['finishing', copy.finishing], ['facades', copy.facades], ['electrical', copy.electricalFilter]].map(([value, text]) => `<button type="button" data-sector="${value}" aria-pressed="${value === ''}">${text}</button>`).join('')}</div>`;
    const dialog = isDocument ? '' : `<dialog class="photo-dialog" data-photo-dialog aria-label="${copy.work}"><div class="photo-bar"><span data-photo-position></span><div class="photo-controls"><button type="button" data-photo-previous aria-label="${copy.prev}">←</button><button type="button" data-photo-next aria-label="${copy.next}">→</button><button type="button" data-photo-close>${copy.close}</button></div></div><img src="/assets/img/icon.svg" alt=""><p class="photo-caption" data-photo-caption></p></dialog>`;
    const hero = `<header class="content-head${isDocument ? ' cooperation-head' : ''}"><div class="content-wrap"><span class="eyebrow on-dark">ARCADIAN</span><h1>${title}</h1>${isDocument ? cooperationOffers(copy, section) : '<p>' + intro + '</p>'}</div>${isDocument ? contactStrip(locale) : ''}</header>`;
    const html = `${head}  <main class="main" data-content-page="${isDocument ? 'documents' : 'gallery'}"${trade ? ` data-content-sector="${trade[0]}"` : section === 'electrical' ? ' data-content-sector="electrical"' : ''}>\n    ${hero}\n    <section class="content-body" aria-label="${title}"><div class="content-wrap">${documentNav}${filters}<p class="content-status" data-content-status role="status">${copy.loading}</p><div class="content-grid"${isDocument ? ' id="rate-documents"' : ''} data-content-list></div><button type="button" class="btn btn-outline content-more" data-content-more hidden>${copy.more}</button><div class="content-cta"><p>${copy.cta}</p><a class="btn btn-copper" href="/${copy.prefix}#contact">${copy.contact}</a></div><noscript><p>${copy.cta} <a href="/${copy.prefix}#contact">${copy.contact}</a></p></noscript></div></section>\n    ${dialog}\n  </main>\n${footer}\n  <script src="/assets/js/arcadian.js"></script>\n  <script src="/assets/js/content-config.js"></script>\n  <script src="/assets/js/content.js?v=cms-v2"></script>\n  <script src="/assets/js/cookie-preferences.js"></script>\n</body>\n</html>\n`;
    const destination = new URL(`${copy.prefix}${section}/`, site);
    await mkdir(destination, {recursive: true});
    await writeFile(new URL('index.html', destination), cleanHtml(html));
  }
}
async function refreshNavigation(directory) {
  for (const entry of await readdir(directory, {withFileTypes: true})) {
    const path = new URL(entry.name + (entry.isDirectory() ? '/' : ''), directory);
    if (entry.isDirectory() && !['assets', 'dist'].includes(entry.name) && !entry.name.startsWith('.')) await refreshNavigation(path);
    if (!entry.isFile() || !entry.name.endsWith('.html')) continue;
    const original = await readFile(path, 'utf8');
    const updated = original.replace(/<nav\b[^>]*\bid="site-nav"[^>]*>[\s\S]*?<\/nav>/g, nav => nav.replace('<small>Engineering Group</small>', ''));
    if (updated !== original) await writeFile(path, updated);
  }
}
await refreshNavigation(site);
console.log('Generated galleries and cooperation pages, and refreshed navigation in EN, PL and NL.');
