import {readFile, mkdir, writeFile} from 'node:fs/promises';

const site = new URL('../static-site/', import.meta.url);
const locales = {
  en: {prefix: '', work: 'Our work', electrical: 'Electrical engineering & installation', rates: 'Work with Arcadian', intro: 'Renovation, finishing and facade work. Photographs and descriptions of completed projects.', electricalIntro: 'Electrical work, documented from design through installation. A dedicated portfolio of our electrical projects.', ratesIntro: 'Cooperation terms for employees, independent specialists and crews. Each published position states the payment basis and what is expected.', all: 'All work', finishing: 'Finishing & renovation', facades: 'Facades', electricalFilter: 'Electrical', loading: 'Loading…', more: 'Show more', cta: 'Discuss your project or cooperation with our team.', contact: 'Contact Arcadian', close: 'Close', prev: 'Previous photograph', next: 'Next photograph', homeIntro: 'Site delivery, documented.', homeDescription: 'Explore completed work or discuss joining our delivery teams.', renovationDescription: 'Finishing, renovation and facade projects, with photographs and scope of work.', electricalDescription: 'A dedicated portfolio for electrical engineering and installation.', ratesDescription: 'Cooperation terms for employees, independent specialists and crews.', open: 'Explore →'},
  pl: {prefix: 'pl/', work: 'Nasze realizacje', electrical: 'Projektowanie i instalacje elektryczne', rates: 'Współpraca z Arcadian', intro: 'Renowacje, wykończenia i elewacje. Zdjęcia oraz opisy zrealizowanych projektów.', electricalIntro: 'Prace elektryczne udokumentowane od projektu po montaż. Osobne portfolio naszych realizacji elektrycznych.', ratesIntro: 'Warunki współpracy dla pracowników, samodzielnych specjalistów i brygad. Każda opublikowana pozycja określa podstawę rozliczenia i wymagania.', all: 'Wszystkie prace', finishing: 'Wykończenia i renowacje', facades: 'Elewacje', electricalFilter: 'Elektryka', loading: 'Ładowanie…', more: 'Pokaż więcej', cta: 'Porozmawiaj z naszym zespołem o projekcie lub współpracy.', contact: 'Kontakt z Arcadian', close: 'Zamknij', prev: 'Poprzednie zdjęcie', next: 'Następne zdjęcie', homeIntro: 'Realizacje i współpraca.', homeDescription: 'Zobacz wykonane prace lub porozmawiaj o dołączeniu do naszych zespołów.', renovationDescription: 'Wykończenia, renowacje i elewacje: zdjęcia i zakres wykonanych prac.', electricalDescription: 'Osobne portfolio projektowania i instalacji elektrycznych.', ratesDescription: 'Warunki współpracy dla pracowników, samodzielnych specjalistów i brygad.', open: 'Zobacz →'},
  nl: {prefix: 'nl/', work: 'Onze werken', electrical: 'Elektrisch ontwerp & installatie', rates: 'Samenwerken met Arcadian', intro: 'Renovatie, afwerking en gevelwerken. Foto’s en beschrijvingen van uitgevoerde projecten.', electricalIntro: 'Elektrische werken, van ontwerp tot installatie gedocumenteerd. Een afzonderlijk portfolio van onze elektrische projecten.', ratesIntro: 'Samenwerkingsvoorwaarden voor werknemers, zelfstandige specialisten en ploegen. Elke gepubliceerde positie vermeldt de betalingsbasis en de verwachtingen.', all: 'Alle werken', finishing: 'Afwerking & renovatie', facades: 'Gevels', electricalFilter: 'Elektriciteit', loading: 'Laden…', more: 'Meer tonen', cta: 'Bespreek uw project of samenwerking met ons team.', contact: 'Contact met Arcadian', close: 'Sluiten', prev: 'Vorige foto', next: 'Volgende foto', homeIntro: 'Werken en samenwerking.', homeDescription: 'Bekijk uitgevoerde werken of bespreek samenwerking met onze ploegen.', renovationDescription: 'Afwerking, renovatie en gevelwerken, met foto’s en de uitgevoerde werkzaamheden.', electricalDescription: 'Een afzonderlijk portfolio voor elektrisch ontwerp en installatie.', ratesDescription: 'Samenwerkingsvoorwaarden voor werknemers, zelfstandige specialisten en ploegen.', open: 'Bekijk →'},
};
const escape = (value) => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
const cleanHtml = (value) => value.replace(/&amp;(nbsp|times);/g, '&$1;').replace(/&(?!(?:amp|lt|gt|quot|nbsp|times|copy);|#[0-9]+;|#x[0-9a-f]+;)/gi, '&amp;').replace(/[ \t]+\n/g, '\n');
for (const [locale, copy] of Object.entries(locales)) {
  const sourceUrl = new URL(`${copy.prefix}index.html`, site);
  let source = await readFile(sourceUrl, 'utf8');
  const links = `<a href="/${copy.prefix}gallery/">${copy.work}</a><a href="/${copy.prefix}rates/">${copy.rates}</a>`;
  source = source.replace(/(<div class="nav-links" id="nav-links">\s*)([\s\S]*?)(\s*<\/div>)/, (_, start, body, end) => `${start}${body.replace(/<a href="[^\"]*\/#team">[\s\S]*?<\/a>/, '').replace(/<a href="[^\"]*\/#about">[\s\S]*?<\/a>/, '')}${body.includes('/gallery/') ? '' : links}${end}`);
  if (!source.includes('/assets/css/content.css')) source = source.replace('</head>', '  <link href="/assets/css/content.css?v=cms-v1" rel="stylesheet">\n</head>');
  if (!source.includes('id="work-and-cooperation"')) {
    const section = `  <section class="lt" id="work-and-cooperation">\n    <div class="content-wrap">\n      <div class="sect-head"><span class="eyebrow">ARCADIAN</span><h2>${copy.homeIntro}</h2><p>${copy.homeDescription}</p></div>\n      <div class="services-entry">\n        <a href="/${copy.prefix}gallery/"><span class="eyebrow">${copy.finishing} · ${copy.facades}</span><h3>${copy.work}</h3><p>${copy.renovationDescription}</p><span class="entry-link">${copy.open}</span></a>\n        <a href="/${copy.prefix}electrical/"><span class="eyebrow">${copy.electricalFilter}</span><h3>${copy.electrical}</h3><p>${copy.electricalDescription}</p><span class="entry-link">${copy.open}</span></a>\n        <a href="/${copy.prefix}rates/"><span class="eyebrow">ARCADIAN</span><h3>${copy.rates}</h3><p>${copy.ratesDescription}</p><span class="entry-link">${copy.open}</span></a>\n      </div>\n    </div>\n  </section>\n\n`;
    source = source.replace('  <section class="lt blueprint products"', section + '  <section class="lt blueprint products"');
  }
  await writeFile(sourceUrl, cleanHtml(source));
  for (const section of ['gallery', 'electrical', 'rates']) {
    const title = section === 'rates' ? copy.rates : section === 'electrical' ? copy.electrical : copy.work;
    const intro = section === 'rates' ? copy.ratesIntro : section === 'electrical' ? copy.electricalIntro : copy.intro;
    let head = source.slice(0, source.indexOf('  <main class="main">'));
    head = head.replace(/<title>[^<]+<\/title>/, `<title>${title} — ARCADIAN</title>`);
    head = head.replace(/(<meta (?:name="description"|property="og:description"|name="twitter:description") content=")[^"]+("[^>]*>)/g, `$1${escape(intro)}$2`);
    head = head.replace(/(<meta (?:property="og:title"|name="twitter:title") content=")[^"]+("[^>]*>)/g, `$1${escape(title)} — ARCADIAN$2`);
    head = head.replace(/(<link rel="canonical" href="https:\/\/arcadian-eu.com\/)[^"]*(">)/, `$1${copy.prefix}${section}/$2`);
    head = head.replace(/(<meta property="og:url" content="https:\/\/arcadian-eu.com\/)[^"]*(">)/, `$1${copy.prefix}${section}/$2`);
    head = head.replace(/(<link rel="alternate" hreflang="(en|nl|pl|x-default)" href=")[^"]+(">)/g, (_, before, lang, after) => `${before}https://arcadian-eu.com/${lang === 'pl' || lang === 'nl' ? lang + '/' : ''}${section}/${after}`);
    head = head.replace(/(<div class="lang">)[\s\S]*?(<\/div>)/, `$1<a href="/gallery/" aria-label="English"${locale === 'en' ? ' class="on"' : ''}>EN</a><a href="/pl/gallery/" aria-label="Polski"${locale === 'pl' ? ' class="on"' : ''}>PL</a><a href="/nl/gallery/" aria-label="Nederlands"${locale === 'nl' ? ' class="on"' : ''}>NL</a>$2`).replaceAll('gallery/" aria-label=', `${section}/" aria-label=`);
    const footer = source.slice(source.indexOf('  <footer'), source.indexOf('</footer>') + '</footer>'.length);
    const filters = section === 'electrical' ? '' : `<div class="content-filters" role="group" aria-label="${copy.work}">${[['', copy.all], ['finishing', copy.finishing], ['facades', copy.facades], ['electrical', copy.electricalFilter]].map(([value, text]) => `<button type="button" data-sector="${value}" aria-pressed="${value === ''}">${text}</button>`).join('')}</div>`;
    const dialog = section === 'rates' ? '' : `<dialog class="photo-dialog" data-photo-dialog aria-label="${copy.work}"><div class="photo-bar"><span data-photo-position></span><div class="photo-controls"><button type="button" data-photo-previous aria-label="${copy.prev}">←</button><button type="button" data-photo-next aria-label="${copy.next}">→</button><button type="button" data-photo-close>${copy.close}</button></div></div><img src="/assets/img/icon.svg" alt=""><p class="photo-caption" data-photo-caption></p></dialog>`;
    const html = `${head}  <main class="main" data-content-page="${section === 'rates' ? 'rates' : 'gallery'}"${section === 'electrical' ? ' data-content-sector="electrical"' : ''}>\n    <header class="content-head"><div class="content-wrap"><span class="eyebrow on-dark">ARCADIAN</span><h1>${title}</h1><p>${intro}</p></div></header>\n    <section class="content-body" aria-label="${title}"><div class="content-wrap">${filters}<p class="content-status" data-content-status role="status">${copy.loading}</p><div class="content-grid" data-content-list></div><button type="button" class="btn btn-outline content-more" data-content-more hidden>${copy.more}</button><div class="content-cta"><p>${copy.cta}</p><a class="btn btn-copper" href="/${copy.prefix}#contact">${copy.contact}</a></div><noscript><p>${copy.cta} <a href="/${copy.prefix}#contact">${copy.contact}</a></p></noscript></div></section>\n    ${dialog}\n  </main>\n${footer}\n  <script src="/assets/js/arcadian.js"></script>\n  <script src="/assets/js/content-config.js"></script>\n  <script src="/assets/js/content.js?v=cms-v1"></script>\n  <script src="/assets/js/cookie-preferences.js"></script>\n</body>\n</html>\n`;
    const destination = new URL(`${copy.prefix}${section}/`, site);
    await mkdir(destination, {recursive: true});
    await writeFile(new URL('index.html', destination), cleanHtml(html));
  }
}
console.log('Generated gallery, electrical and cooperation pages in EN, PL and NL.');
