# Generated by Django 5.2.17 on 2026-10-04 19:53

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRateDocument',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='Название (EN или общий текст)')),
                ('description', models.TextField(blank=True, max_length=6000, verbose_name='Описание (EN или общий текст)')),
                ('title_pl', models.CharField(blank=True, max_length=180, verbose_name='Название PL')),
                ('title_nl', models.CharField(blank=True, max_length=180, verbose_name='Название NL')),
                ('description_pl', models.TextField(blank=True, max_length=6000, verbose_name='Описание PL')),
                ('description_nl', models.TextField(blank=True, max_length=6000, verbose_name='Описание NL')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архив')], default='draft', max_length=12, verbose_name='Состояние')),
                ('sort', models.PositiveIntegerField(default=0, help_text='Меньшее число — выше в списке.', verbose_name='Порядок')),
                ('revision', models.PositiveIntegerField(default=0, editable=False, verbose_name='Версия')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Изменено')),
                ('category', models.CharField(choices=[('electrical', 'Электрики'), ('facades', 'Фасадчики'), ('finishing', 'Отделочники'), ('subcontractors', 'Субподрядчики — бригады')], max_length=20, verbose_name='Раздел сайта')),
                ('visibility', models.CharField(choices=[('private', 'Внутренняя'), ('public', 'Публичная')], default='public', help_text='Публичный PDF появится на сайте после выбора «Опубликовано». Внутренний PDF доступен только редактору.', max_length=10, verbose_name='Видимость')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('file_key', models.CharField(blank=True, editable=False, max_length=250)),
                ('file_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('file_bytes', models.PositiveIntegerField(default=0, editable=False)),
                ('page_count', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical PDF с расценками',
                'verbose_name_plural': 'historical Расценки',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RateDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='Название (EN или общий текст)')),
                ('description', models.TextField(blank=True, max_length=6000, verbose_name='Описание (EN или общий текст)')),
                ('title_pl', models.CharField(blank=True, max_length=180, verbose_name='Название PL')),
                ('title_nl', models.CharField(blank=True, max_length=180, verbose_name='Название NL')),
                ('description_pl', models.TextField(blank=True, max_length=6000, verbose_name='Описание PL')),
                ('description_nl', models.TextField(blank=True, max_length=6000, verbose_name='Описание NL')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архив')], default='draft', max_length=12, verbose_name='Состояние')),
                ('sort', models.PositiveIntegerField(default=0, help_text='Меньшее число — выше в списке.', verbose_name='Порядок')),
                ('revision', models.PositiveIntegerField(default=0, editable=False, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('category', models.CharField(choices=[('electrical', 'Электрики'), ('facades', 'Фасадчики'), ('finishing', 'Отделочники'), ('subcontractors', 'Субподрядчики — бригады')], max_length=20, verbose_name='Раздел сайта')),
                ('visibility', models.CharField(choices=[('private', 'Внутренняя'), ('public', 'Публичная')], default='public', help_text='Публичный PDF появится на сайте после выбора «Опубликовано». Внутренний PDF доступен только редактору.', max_length=10, verbose_name='Видимость')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('file_key', models.CharField(blank=True, editable=False, max_length=250)),
                ('file_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('file_bytes', models.PositiveIntegerField(default=0, editable=False)),
                ('page_count', models.PositiveSmallIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'PDF с расценками',
                'verbose_name_plural': 'Расценки',
                'ordering': ['sort', '-created_at', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'visibility', 'category', 'sort'], name='content_rat_status_e116d3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), models.Q(models.Q(('file_key', ''), _negated=True), ('file_bytes__gt', 0), ('page_count__gt', 0)), _connector='OR'), name='rate_document_published_file')],
            },
        ),
    ]
