# Generated by Django 5.2.17 on 2026-10-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rate_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalratedocument',
            name='translations',
            field=models.JSONField(blank=True, db_default={}, default=dict, editable=False, verbose_name='Дополнительные PDF'),
        ),
        migrations.AddField(
            model_name='ratedocument',
            name='translations',
            field=models.JSONField(blank=True, db_default={}, default=dict, editable=False, verbose_name='Дополнительные PDF'),
        ),
    ]
